name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bash_unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: AnimMouse/setup-ffmpeg@v1
    - run: sudo apt-get install -y exiftool
    - name: Unit testing with bash_unit
      run: |
        bash <(curl -s https://raw.githubusercontent.com/pgrange/bash_unit/master/install.sh)
        FORCE_COLOR=true ./bash_unit ./test/test*
